### ISSUE TITLE
Feature & Release checklist

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Bootloader#6]
## MODE

There are 2 bootloader modes: DFU serial (default) and OTA.  In both modes, msc uf2 is supported with nrf52840.  

### Serial + UF2

- [ ] [**Physical**] **DFU** pin = low (short hold) , **FRST** pin = high
- [ ] [**PCdriver**] [**52840**] disconnect serial at 1200bps (arduino friendly)
- [ ] [**PCdriver**] [**52840**] a custom USB command with control endpoint
- [ ] [**Firmware**] Application code make a request  using power register GPREGRET = serial magic ( 0x4E )
- [ ] [**Auto**] Serial mode entered when there is no valid application code
- [ ] **DFU** = high, **FRST** = low: **Factory Reset**, erase Application Code & Application Data then continue to Serial mode.
- [ ] [**52832**] DFU Startup:  DFU Serial is automatically entered whenever power on (even without any DFU condition) for 1 seconds for uploading sketch from Arduino IDE</s>

### OTA + UF2

- [ ]  [**Physical**]  **DFU** = low , **FRST** = low
- [ ]  [**Physical**]  **DFU** = low with long holding (e.g 5 seconds) until BLUE LED is blinking
- [ ] [**PCdriver**] [**52840**] disconnect serial at 2400 bps 
- [ ] [**PCdriver**] [**52840**] a custom USB command with control endpoint 
- [ ] [**Firmware**]  Application code make a request  using power register GPREGRET = ota magic ( 0xA8 )
- [ ] [**BLE Central**] Write to BLE DFU service

## INDICATOR

- [ ] DFU Serial : LED_RED is blinking fast (200ms), and 2x (100ms) when uploading
- [ ] DFU OTA : LED_RED & LED_BLUE are blinking fast, LED_BLUE stay on when connected, LED_RED blink 2x when uploading
- [ ] Factory Reset: RED will blink 2x, BLUE is turn on when erasing (very brief).

## BEHAVIOR

- [ ] DFU OTA timeout is 300 seconds ~ 5 minutes
- [ ] DFU OTA, Device Information should have
  - [ ] Adv Name is `AdaDFU`
  - [ ] Manufacture String is `Adafruit Industries`
  - [ ] Model String is `Bluefruit Feather nRF528xx` (xx is either 32 or 40)
  - [ ] Firmware String is `SDname SDversion rRev` e.g `S132 6.1.0 r0`
- [ ] DFU (Serial & OTA) only accept firmware built for it
  - [ ] 840 reject 832's application
  - [ ] 840 reject 832's bootloader package (sd + boot)
  - [ ] 840 reject 832's application uf2
  - [ ] 832 reject 840's application
  - [ ] 832 reject 840's bootloader package (sd + boot)
- [ ] Update zip file from iOS/Android
- [ ] Test upgrading modified bootloader of the same SD version
- [ ] Test upgrading to different SD major version e.g v5 to v6

**IDE**

- [ ] Burn bootloader on OSX/Windows/Linux
- [ ] Upload sketch on OS/Windows/Linux
- [ ] Upload sketch with Serial opened on OS/Windows/Linux
- [ ] <strike>Download sketch via OTA with OSX</strike> Reason: missing OTA CLI that support package zip file. 
- [ ] Test with latest Arduino IDE
